# Standalone `cmake -P` script (invoked via add_custom_command, not
# include()'d): embeds INPUT_FILE as a byte array named VAR_NAME in a
# generated C source, OUTPUT_FILE. This is how the web GUI's frontend
# (assets/index.html) ends up compiled into the executable rather than
# shipped as a separate file - the release tarball (Phase 15) and the
# binary stay a single self-contained thing, and there is nothing on
# disk a user could accidentally edit or lose. Pure CMake, no external
# tool (xxd, python, ...): one dependency less to require at build time,
# matching this project's own "no dependency you do not need" stance
# for the product itself.
#
# A hex byte array rather than a big C string literal: index.html's own
# content freely contains quotes and backslashes (its inline <script>
# especially), which a string literal would need to escape correctly;
# a byte array needs no escaping at all, whatever bytes the file
# contains.
if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE OR NOT DEFINED VAR_NAME)
    message(FATAL_ERROR "EmbedAsset.cmake requires -DINPUT_FILE=, -DOUTPUT_FILE=, and -DVAR_NAME=")
endif()

file(READ "${INPUT_FILE}" file_hex HEX)
string(LENGTH "${file_hex}" hex_len)
math(EXPR byte_len "${hex_len} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," byte_array "${file_hex}")

file(WRITE "${OUTPUT_FILE}"
"/* Generated by EmbedAsset.cmake from ${INPUT_FILE}. Do not edit by hand. */
#include <stddef.h>

const unsigned char ${VAR_NAME}[] = {${byte_array}0x00};
const size_t ${VAR_NAME}_len = ${byte_len};
")
